
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

oauth_register:
    pattern: /oauthRegister
    defaults: { _controller: AppBundle:Security:oauthRegister }
my_oauth:
    resource: "@AppBundle/Resources/config/routingSecurityOAuth.yml"
    prefix:   /oauth/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /


_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_user_security_check:
    defaults: { _controller: UserBundle:Security:login }
    path:   /login

