# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
  app.oauth_members.class: AppBundle\Services\OAuthMembersService


services:

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    my_oauth_members:
        class: %app.oauth_members.class%
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]